# Generated by Django 5.2 on 2025-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("whatsapp_number", models.CharField(max_length=20)),
                ("video", models.URLField(blank=True, max_length=500, null=True)),
                ("thumbnail", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ В ожидании"),
                            ("processing", "⚙️ Обработка"),
                            ("done", "✅ Готово"),
                            ("failed", "❌ Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
