# Generated by Django 5.2 on 2025-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="whatsapp_link",
        ),
        migrations.AddField(
            model_name="product",
            name="whatsapp_number",
            field=models.CharField(
                default=996555606094,
                help_text="Номер продавца для связи",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(help_text="Категория товара", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="city",
            field=models.CharField(help_text="Город", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="Описание товара"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Цена в сомах", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Обложка видео",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(help_text="Название товара", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(
                help_text="Видео товара (до 30 сек)", upload_to="videos/"
            ),
        ),
    ]
