# Generated by Django 5.2 on 2025-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_remove_product_whatsapp_link_product_whatsapp_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(
                blank=True, help_text="Видео до 30 сек", null=True, upload_to="videos/"
            ),
        ),
    ]
