# Generated by Django 5.2 on 2025-05-03 09:02

import products.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="city",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=products.models.product.thumbnail_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(
                default="media/placeholder.mp4",
                upload_to=products.models.product.video_upload_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="whatsapp_number",
            field=models.CharField(max_length=20),
        ),
    ]
