# Generated by Django 5.2 on 2025-05-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_category_remove_product_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "⏳ В ожидании"),
                    ("processing", "⚙️ Обработка"),
                    ("done", "✅ Готово"),
                    ("failed", "❌ Ошибка"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
