# Generated by Django 5.2 on 2025-05-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", " В ожидании"),
                    ("processing", " Обработка"),
                    ("done", " Готово"),
                    ("failed", " Ошибка"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
